repos:
  # - repo: https://github.com/gitguardian/ggshield
  #   rev: main
  #   hooks:
  #     - id: ggshield
  #       language_version: python3
  #       stages: [commit]
  # -   repo: https://github.com/pre-commit/mirrors-jshint
  #     rev: ''  # Use the sha / tag you want to point at
  #     hooks:
  #     -   id: jshint

  # -   repo: https://github.com/pre-commit/mirrors-prettier
  #     rev: ''  # Use the sha / tag you want to point at
  #     hooks:
  #     -   id: prettier
  #         additional_dependencies:
  #         -   prettier@2.7.1
  #         -   '@prettier/plugin-xml@0.12.0'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha / tag you want to point at
    # files: ^src/
    # exclude: ^.github/
    # exclude: |
    #   (?x)(
    #       ^.github/|
    #       ^src/config/
    #   )
    hooks:
      - id: prettier
        exclude: |
          (?x)^(
              .github/.*|
              src/config/.*
          )$
        # types_or: [javascript]
