apiVersion: v1
kind: Service
metadata:
    annotations:
        kompose.cmd: kompose convert
        kompose.controller.type: deployment
        kompose.service.export: 'true'
        kompose.service.type: nodeport
        kompose.version: 1.21.0 ()
    creationTimestamp: null
    labels:
        io.kompose.service: butler
    name: butler
spec:
    ports:
        - name: '8080'
          port: 8080
          targetPort: 8080
        - name: '9997'
          port: 9997
          targetPort: 9997
        - name: '9998'
          port: 9998
          targetPort: 9998
    selector:
        io.kompose.service: butler
    type: NodePort
status:
    loadBalancer: {}
