butlerSchedule:
  - name: Every 30 sec
    cronSchedule: '*/30 * * * * *'
    timezone: Europe/Stockholm
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    startupState: started
    tags:
      - Sales
      - abc 123 åäö
      - Transform
    id: task-1
    lastKnownState: started
  - name: Every 2 hours on top of the hour
    cronSchedule: '0 */2 * * *'
    timezone: Europe/London
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    startupState: started
    tags:
      - Finance
      - Extract
    id: task-2
    lastKnownState: started
  - name: >-
      Every 5th minute from 0 through 30 past every hour from 6 through 18 on
      every day-of-week from Monday through Friday
    cronSchedule: '0-30/5 6-18 * * 1-5'
    timezone: Europe/Paris
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    startupState: started
    tags:
      - finance ETL
      - weekdays
    id: Manually-added-schedule-1
    lastKnownState: started
