butlerSchedule:
  - name: Schedule 1
    cronSchedule: '*/15 * * * * *'
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    tags:
      - tag 3
      - abc 123 åäö
    id: 1a
    stateStartupStarted: true
    created: '2020-09-27T08:32:12.864Z'
    timezone: Europe/Stockholm
    stateStarted: true
  - name: New schedule 123åäö
    cronSchedule: '*/5 * * * * *'
    timezone: Europe/Stockholm
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    tags:
      - tag 3
      - abc 123 åäö
    id: 9c0e2423-96d4-425c-892e-18c92f76325f
    stateStartupStarted: true
    created: '2020-09-28T05:00:42.325Z'
    stateStarted: true
