butlerSchedule:
  - name: Every 30 sec
    cronSchedule: "*/30 * * * * *"
    timezone: Europe/Stockholm
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    startupState: started
    tags:
      - tag 2
      - abc 123 åäö
    id: c7ec214c-e9ca-40b2-acb4-54648f90dd73
    created: '2020-09-29T14:29:12.283Z'
    lastKnownState: started