butlerSchedule:
  - name: Every 2 hours
    cronSchedule: '* */2 * * *'
    timezone: Europe/London
    qlikSenseTaskId: 0fe447a9-ba1f-44a9-ac23-68c3a1d88d8b
    startupState: started
    tags:
      - tag 3
      - abc 123 åäö
    id: 3702cec1-b6c8-463e-bda3-58d6a94dd9ac
    created: '2021-10-08T07:24:38.373Z'
    lastKnownState: started
