name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Show github.ref
        run: echo "$GITHUB_REF"

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        if: |
          github.repository_owner == 'ptarmiganlabs'
        with:
          command: manifest


# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: GoogleCloudPlatform/release-please-action@v2.32.0
#         if: |
#           github.repository_owner == 'ptarmiganlabs'
#         with:
#           token: ${{ secrets.PAT }}
#           release-type: node
#           package-name: butler
#           default-branch: master
#           path: src
